models.py
from utils import db


class Produto(db.Model):
    __tablename__ = 'pedidos'
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(100))
    categoria = db.Column(db.String(200))
    quantidade = db.Column(db.Integer)
    preco = db.Column(db.Float)


    def __init__(self, nome, categoria, quantidade, preco):
        self.nome = nome
        self.categoria = categoria
        self.quantidade = quantidade
        self.preco = preco
    
    def __repr__(self):
        return "<Pedido {} - {} - {} - {}>".format(self.pedido.nome, self.pedido.categoria, self.pedido.quantidade, self.pedido.preco)

app.py
from flask import Flask, render_template, request, redirect, Blueprint, url_for
from utils import db
from models import Produto
from flask_migrate import Migrate
from routes.principal import home_route
from routes.produto import produto_route


app = Flask(__name__)

app.secret_key = 'minha_chave_secreta'

conexao = "sqlite:///meubanco.sqlite"
app.config['SQLALCHEMY_DATABASE_URI'] = conexao
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


db.init_app(app)


migrate = Migrate(app, db)

app.register_blueprint(home_route)
app.register_blueprint(produto_route, url_prefix='/produto')




if __name__ == '__main__':
    app.run()

routes/principal.py
from flask import  Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('principal.html')

routes/produto.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from utils import db
from models import Produto

produto_route = Blueprint('produto', __name__)

@produto_route.route('/listar_produtos')
def listagem_produtos():
    lista_produto = Produto.query.all()
    return render_template('listar.html', lista=lista_produto)

@produto_route.route('/cadastrar')
def cadastrar_produto():
    return render_template('cadastrar.html')

@produto_route.route('/cadastrar_enviar', methods=['POST'])
def cadastrar_enviar_produto():
    nome = request.form['nome']
    categoria = request.form['categoria']
    
    
    quantidade = request.form['quantidade'] or 0  
    preco = request.form['preco'] or 0.0  
    
    try:
        quantidade = int(quantidade) 
        preco = float(preco)  
    except ValueError:
        flash('Quantidade e preço devem ser valores numéricos!', 'danger')
        return redirect(url_for('produto.cadastrar_produto'))

    p = Produto(nome=nome, categoria=categoria, quantidade=quantidade, preco=preco)

    db.session.add(p)
    db.session.commit()
    
    flash('Produto cadastrado com sucesso!', 'success')
    
    # Redirecionar de volta para a página de cadastro
    return redirect(url_for('produto.cadastrar_produto'))

@produto_route.route('/editar_produto/<int:id_produto>')
def editar(id_produto):
    p = Produto.query.get(id_produto)
    return render_template('editar.html', dados_produto=p)

@produto_route.route('/editar_enviar', methods=['POST'])
def editar_enviar():
    id_produto = request.form['id_produto']
    nome = request.form['nome']
    categoria = request.form['categoria']
    
    # Validação para quantidade e preço
    quantidade = request.form['quantidade'] or 0
    preco = request.form['preco'] or 0.0
    
    try:
        quantidade = int(quantidade)
        preco = float(preco)
    except ValueError:
        flash('Quantidade e preço devem ser valores numéricos!', 'danger')
        return redirect(url_for('produto.editar', id_produto=id_produto))

    p = Produto.query.get(id_produto)
    p.nome = nome
    p.categoria = categoria
    p.quantidade = quantidade
    p.preco = preco

    db.session.add(p)
    db.session.commit()

    flash('Produto editado com sucesso!', 'success')
    return redirect(url_for('produto.listagem_produtos'))

@produto_route.route('/excluir/<int:id_produto>')
def excluir(id_produto):
    p = Produto.query.get(id_produto)

    db.session.delete(p)
    db.session.commit()

    flash('Produto excluído com sucesso!', 'danger')
    return redirect(url_for('produto.listagem_produtos'))

templates/cadastrar.html
{% extends "fonte.html" %}


{% block titulo %}
- CADASTRO
{% endblock %}

{% block conteudo %}
<div class="telaCad">
  <h1 class="titleareaCad">Cadastrar Produto </h1>
  <div class="areaCad">
    <form action="{{ url_for('produto.cadastrar_enviar_produto') }}" method="post">
      <div class="barra1">
        <p>Nome:</p>
        <p><input type="text" name="nome" class="blockCad" /></p>
        <p>Categoria:</p>
        <p><input type="text" name="categoria" class="blockCad" /></p>
      </div>
      <div class="barra1">
        <p>Quantidade:</p>
        <p><input type="number" name="quantidade" class="blockCad" /></p>
        <p>Preço:</p>
        <p><input type="number" step="0.01" name="preco" class="blockCad" /></p>
      </div>
      <p class="buttonCad"><button type="submit">Cadastrar</button></p>
    </form>
  </div>
</div>

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="flash-messages">
  {% for category, message in messages %}
  <div class="alert alert-{{ category }}">
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}
{% endwith %}
{% endblock %}

templates/editar.html
{% extends "fonte.html" %}

{% block titulo %}
- Editar
{% endblock %}

{% block conteudo %}
<div class="telaCad">
    <h1 class="titleareaCad">Editar Produto</h1>
    <div class="areaCad">
        <form action="/produto/editar_enviar" method="post">
            <div class="barra1">
                <p><input type="hidden" name="id_produto" class="blockCad" value="{{dados_produto['id']}}"></p>
                <p>Nome: <input type="text" name="nome" class="blockCad" value="{{dados_produto['nome']}}" /></p>
                <p>Categoria: <input type="text" name="categoria" class="blockCad" value="{{dados_produto['categoria']}}" /></p>
            </div>
            <div class="barra1">
                <p>Quantidade: <input type="number" name="quantidade" class="blockCad" value="{{dados_produto['quantidade']}}"></p>
                <p>Preço: <input type="number" step="0.01" name="preco" class="blockCad" value="{{dados_produto['preco']}}"></p>
            </div>
            <p class="buttonCad"><button type="submit">Salvar</button></p>
        </form>
    </div>
</div>



{% endblock %}

templates/fonte.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Cadastro de Produtos {% block titulo %} {% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for ('static', filename = '/css/estilo.css' )}}">
</head>

<body class="
    {% if request.path == '/produto/cadastrar' %}
        cadastrar
    {% elif request.path == '/produto/listar_produtos' %}
        listar-Produtos
    {% elif request.path.startswith('/produto/editar/') %}
        editar
    {% endif %}
">
  {% if request.path == '/' %}
  <img class="fundo" src="https://content.paodeacucar.com/wp-content/uploads/2019/06/8-dicas-%C3%BAteis-2.jpg">
  {% endif %}

  <ul>
    <div class="opcoes">
      <li><a href="/">Home</a></li>
      <li><a href="{{ url_for('produto.cadastrar_produto') }}">Cadastrar</a></li>
      <li><a href="{{ url_for('produto.listagem_produtos') }}">Listar</a></li>
    </div>
  </ul>
  {% block conteudo %}

  {% endblock %}

   
</body>

</html>

templates/listar.html
{% extends "fonte.html" %}

{% block conteudo %}
<div class="listaCad">
    <h1 class="titleCad">Produtos Cadastrados</h1>
    <div class="tableCad">
        <table>
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Nome</td>
                    <td>Categoria</td>
                    <td>Quantidade</td>
                    <td>Preço</td>
                    <td> </td>
                    <td> </td>
                </tr>
            </thead>
            <tbody>
                {% for item in lista %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.nome}}</td>
                    <td>{{item.categoria}}</td>
                    <td>{{item.quantidade}}</td>
                    <td>{{item.preco}}</td>
                    <td><a class="editar" href="/produto/editar_produto/{{item.id}}">Editar</a></td>
                    <td><a href="/produto/excluir/{{item.id}} ">Excluir</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="flash-messages">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="flash-messages">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}



{% endblock %}

templates/principal.html
{% extends "fonte.html" %}

{% block titulo %}
- INICIAL
{% endblock %}

{% block conteudo %}
<div  class="titleInicial">
    <h1>MERCADINHO <br> <scan class="title2"> SÃO FRANCISCO </scan></h1> 

</div>




{% endblock %}